### ISSUE TITLE
Check code into this repo

### ISSUE THREAD

**Issue by elijahlofgren** [HackMGM/afitc-conf-app#5]
@jacquelineflemming if it isn't too hard could you check the code you've deployed from the pinax project into this repo so we can look into adding some of the enhancements Boyd has suggested?

Thanks!
- Elijah

**Comment by jacquelineIO** [comment]
Definitely can do that. I will do it after work some time today when I have my laptop.

**Comment by elijahlofgren** [comment]
Thanks for checking it in!
